# -*- coding: utf-8 -*-
"""player_report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7Sj4mmNo3tPKLpOY66M9O5dRJiiutIH
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Almabetter/Notebook/ct_2025_deliveries.csv')
df.head()

df.drop(['season','phase','match_no','date','venue'],axis=1,inplace=True)
df

match_id = df['match_id'].unique().tolist()
match_id

df_batsman = pd.DataFrame()

df_batsman = df[(df['wide']==0)|(df['legbyes']==0)|(df['byes']==0)].groupby(['match_id','batting_team','striker']).agg({'runs_of_bat':'sum'})
df_batsman['bowl_faced'] = df[(df['extras']==0)|~(df['byes']==0)|~(df['legbyes']==0)].groupby(['match_id','batting_team','striker']).agg({'runs_of_bat':'count'})
df_batsman['4s'] = df[df['runs_of_bat']==4].groupby(['match_id','batting_team','striker']).agg({'runs_of_bat':'count'})
df_batsman['6s'] = df[df['runs_of_bat']==6].groupby(['match_id','batting_team','striker']).agg({'runs_of_bat':'count'})
df_batsman['strike_rate'] = df_batsman['runs_of_bat']*100/df_batsman['bowl_faced']

df_wickets = df[~df['wicket_type'].isnull()][['match_id','batting_team','player_dismissed','wicket_type','bowler','fielder','bowling_team']]
df_wickets

df['bat_and_extra_runs'] = df['runs_of_bat']+df['extras']
df.head()

df_bowler = pd.DataFrame()
df_bowler['runs'] = df[(df['byes']==0)&(df['legbyes']==0)].groupby(['match_id','bowling_team','bowler']).agg({'bat_and_extra_runs':'sum'})

df_bowler['overs'] = df[(df['wide']==0)&(df['noballs']==0)].groupby(['match_id','bowling_team','bowler']).agg({'runs_of_bat':'count'})
df_bowler['wickets'] = df_wickets[~(df_wickets['wicket_type']=='runout')].groupby(['match_id','bowling_team','bowler']).agg({'player_dismissed':'count'})
df_bowler['economy'] = df_bowler['runs']/df_bowler['overs']*6

df_bowler['wide_count'] = df[~(df['wide']==0)].groupby(['match_id','bowling_team','bowler']).agg({'runs_of_bat':'count'})
df_bowler['wide_runs'] = df[~(df['wide']==0)].groupby(['match_id','bowling_team','bowler']).agg({'extras':'sum'})
df_bowler['noball_count'] = df[~(df['noballs']==0)].groupby(['match_id','bowling_team','bowler']).agg({'runs_of_bat':'count'})
df_bowler['noball_runs'] = df[~(df['noballs']==0)].groupby(['match_id','bowling_team','bowler']).agg({'extras':'sum'})

df_match_summary = pd.DataFrame()

df

df_match_summary['team1'] = df[df['innings']==1].groupby(['match_id','batting_team']).agg({'bat_and_extra_runs':'sum'})
df_match_summary['wickets1'] = df[(df['innings']==1)&~(df['wicket_type'].isnull())].groupby(['match_id','batting_team']).agg({'player_dismissed':'count'})
df_match_summary['team1_overs'] = df[df['innings']==1].groupby(['match_id','batting_team']).agg({'over':'max'})

dfms1 = df_match_summary.reset_index().set_index('match_id')
dfms1

dfms2 = pd.DataFrame()
dfms2['team2'] = df[df['innings']==2].groupby(['match_id','batting_team']).agg({'bat_and_extra_runs':'sum'})
dfms2['wickets2'] = df[(df['innings']==2)&~(df['wicket_type'].isnull())].groupby(['match_id','batting_team']).agg({'player_dismissed':'count'})
dfms2['team2_overs'] = df[df['innings']==2].groupby(['match_id','batting_team']).agg({'over':'max'})

dfms = dfms2.reset_index().set_index('match_id')
dfms

df_match_summary = pd.merge(dfms1,dfms,on='match_id')
df_match_summary

df_batsman.reset_index(inplace=True)
df_bowler.reset_index(inplace=True)

df_batsman.to_csv('batsman.csv',index=False)
df_bowler.to_csv('bowler.csv',index=False)
df_match_summary.to_csv('match_summary.csv')
df_wickets.to_csv('wickets.csv',index=False)

